'use strict';
import { StyleSheet, Dimensions } from 'react-native';
export const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
    home_container: {
        alignContent: 'center',
        paddingTop: 50,
        paddingHorizontal: 30,
        backgroundColor: '#ffffff',
        flex: 1,
    },
    header: {
        fontSize: 20,
        alignSelf: 'center',
        paddingBottom: 10,
    },
    text: {
        fontSize: 18,
        alignSelf: 'center',
        paddingBottom: 5,
    },
    button: {
        backgroundColor: '#00aeef',
        borderRadius: 15,
        padding: 10,
        width: "30%",
        alignSelf: 'center',
        margin: 5,
    },
    buttonText: {
        color: 'white',
        alignSelf: 'center',
        fontSize: 15,
        textTransform: 'uppercase'
    },
    container: {
        backgroundColor: '#ffffff',
        flex: 1,
    },
    imageRound: {
        width: 150,
        height: 150,
        borderRadius: 150/2,
        alignSelf: 'center',
    },
    imageSquare: {
        width: '100%',
        height: '100%',
        alignSelf: 'center',
    },
    boxContainer: {
        margin: 5,  
        flex:1, 
        flexDirection: 'row', 
        height: 180,
        alignSelf: 'center',
        shadowOffset: { width: 2, height: 2, },
        shadowColor: '#c2c2c2',
        borderWidth: 0.5,
        borderRadius: 2,
        borderColor: 'transparent',
        borderBottomWidth: 0,
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 1,
    },
    indicator: {
        flex: 1,
        justifyContent: 'center',
        height: 80
    },
    textView: {
        width: '70%',
        fontSize: 20,
        padding: 10,
        color: '#000'
    },
    row: {
        flex: 1,
        flexDirection: 'row',
        padding: 15,
        alignItems: 'center',
    },
    greyButton: {
        backgroundColor: '#c2c2c2',
        margin: 5,
        borderRadius: 15,
        padding: 10,
        width: "30%",
        alignSelf: 'center',
    },
    content: {
        flex: 1,
        backgroundColor: 'white',
        padding: 20,
        margin: 10,
        shadowOffset: { width: 2, height: 2, },
        shadowColor: '#c2c2c2',
        borderWidth: 0.5,
        borderRadius: 2,
        borderColor: '#ddd',
        borderBottomWidth: 0,
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 1,
    },
    contentContainer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: 'white',
        padding: 20,
        margin: 5,
        shadowOffset: { width: 2, height: 2, },
        shadowColor: '#c2c2c2',

        borderWidth: 0.5,
        borderRadius: 2,
        borderColor: '#ddd',
        borderBottomWidth: 0,
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 1,
    },
    item: {
        padding: 5,
        backgroundColor: 'white',
        shadowOffset: { width: 2, height: 2, },
        shadowColor: '#c2c2c2',
        borderWidth: 0.5,
        borderRadius: 2,
        borderColor: '#ddd',
        borderBottomWidth: 0,
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 1,
        position: 'absolute',
        justifyContent: 'flex-end',
        alignSelf: 'flex-end',
        opacity: 0.9,
        width: "100%"
    },
    proButton:{
        backgroundColor: '#00aeef',
        borderRadius: 10,
        padding: 10,
        width: "40%",
        alignSelf: 'center',
        margin: 5,
    },
    loading: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
        alignItems: 'center',
        justifyContent: 'center'
    },
    lessonHeading:{
        fontSize: 15,
        letterSpacing: 2,
        alignSelf: 'center',
        textTransform: 'uppercase',
        textAlign: 'center',
        padding: 10,
    },
    swipe: {
        width,
        // backgroundColor: 'thistle' ,
        paddingBottom: 10,

    },
    child: {
        height: height * 0.5,
        width,
        justifyContent: 'center'
    },
    buttonBorder: {
        borderRadius: 10,
        borderColor: '#818181',
        margin: 5,
        paddingVertical: 5,
        paddingHorizontal: 15,
        backgroundColor: 'white',
        borderWidth: 1,
        alignItems: 'center',
    },
    unselected: {
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        width: 60,
        height: 60,
        backgroundColor: '#fff',
        borderRadius: 60,
    },
    surprised: {
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        width: 60,
        height: 60,
        backgroundColor: '#bfc600',
        borderRadius: 60,
    },
    angry: {
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        width: 60,
        height: 60,
        backgroundColor: '#f0002b',
        borderRadius: 60,
    },
    relaxed: {
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        width: 60,
        height: 60,
        backgroundColor: '#00c656',
        borderRadius: 60,
    },
    cry: {
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        width: 60,
        height: 60,
        backgroundColor: '#0091c9',
        borderRadius: 60,
    },
    love: {
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        width: 60,
        height: 60,
        backgroundColor: '#6f5ec9',
        borderRadius: 60,
    },
    pagination:{
        position: 'absolute',
        top: 340,
        height: 5,
    },
    description:{
        fontSize: 14,
        paddingVertical: 10,
        paddingHorizontal: 20,
        alignSelf: 'center',
    }
});
